### ISSUE TITLE
File .spb

### ISSUE THREAD

**Issue by rafaelbaiolim** [zhangshiqian1214/godot-module#1]
Sorry, it's not a "issue" properly, but, how do i generate the c2s.spb file ? I'll always need this file? 
Or, i need always use the c2s.spb dat you generated? Thank you

**Comment by zhangshiqian1214** [comment]
this use sproto like protobuf. protobuf genernated c2s.pb, sproto can genernated c2s.spb. here is the https://github.com/cloudwu/sproto，easy use a lua script to create c2s.spb or other spb file.

**Comment by zhangshiqian1214** [comment]
here is i generate spb tool:https://github.com/zhangshiqian1214/sproto-tool?files=1

**Comment by rafaelbaiolim** [comment]
Got it, everything is working here now, thank you very much !
