### ISSUE TITLE
Sproto Godot with TCP and Node Js

### ISSUE THREAD

**Issue by rafaelbaiolim** [zhangshiqian1214/godot-module#2]
Hello, did you tried use your module with TCP implementation of godot and a Node Js server? 
I spent the last weekend trying figure out, how sent the packaged buffer to socket but it's goes as 
RawArray and back as String, do you have any idea how implement the server side to read or just transmit 
the buffer as a sproto ?
You think, is better/easy, use other server implementation? Thank you

**Comment by zhangshiqian1214** [comment]
Yes, I used this module and godot's Tcp implemenation, but I not use Node Js Server, I used a network framework named skynet [](https://github.com/cloudwu/skynet), you can try it, also eay and very efficient.

**Comment by rafaelbaiolim** [comment]
Thank you again, worked with a simple tcp implementation + your sproto module 
It helped me a lots !
