### ISSUE TITLE
老哥，能帮忙升级一下godot4.0吗

### ISSUE THREAD

**Issue by huahuacn** [zhangshiqian1214/godot-module#4]
我花了一天时间试着修复了一些，但是到gd_sproto.h里面的一些c++编译错误，就不知道怎么修复了，不太会c++。。。

**Comment by zhangshiqian1214** [comment]
很抱歉, 很久没有用godot了, 里面的godot core可能有了比较大的变化, 所以我建议你可以找一下开源的protobuf实现

**Comment by huahuacn** [comment]
好的，感谢，我后来又试了试，主要是宏改了，感觉改不来，放弃了，感谢~
